controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# handleSearch:
#     path: /handleSearch
#     controller: App\Controller\SearchController::handleSearch
